=== wso2-extensions/tomcat-extension-openidsso/modules/oidcsso/src/main/resources/wso2/oidc-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.

 WSO2 Inc. licenses this file to you under the Apache License,
 Version 2.0 (the "License"); you may not use this file except
 in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0" elementFormDefault="qualified"
           xmlns="http://wso2.org/2016/oidc-config" targetNamespace="http://wso2.org/2016/oidc-config">

    <xs:element name="oidc-config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="enable" type="xs:boolean" minOccurs="0" maxOccurs="1" default="false"/>
                <xs:element name="client-id" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="client-secret" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="redirect-uri" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
                <xs:element name="scope" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="claims" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="response-type" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="grant-type" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="authentication-endpoint" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
                <xs:element name="token-endpoint" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
                <xs:element name="user-info-endpoint" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
                <xs:element name="logout-endpoint" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
                <xs:element name="trust-store" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="location" type="xs:anyURI"/>
                            <xs:element name="type" default="JKS">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="JKS"/>
                                        <xs:enumeration value="PKCS11"/>
                                        <xs:enumeration value="PKCS12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="key-alias" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== wso2-extensions/tomcat-extension-openidsso/modules/oidcsso/src/main/resources/wso2/oidc-config.xml
<?xml version="1.0" encoding="utf-8"?>

<oidc-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://wso2.org/2016/oidc-config"
             xsi:schemaLocation="http://wso2.org/2016/oidc-config oidc-config.xsd">


    <enable>false</enable>
    <scope>openid</scope>
    <response-type>code</response-type>
    <grant-type>authorization_code</grant-type>
    <authentication-endpoint>https://localhost:9443/oauth2/authorize</authentication-endpoint>
    <token-endpoint>https://localhost:9443/oauth2/token</token-endpoint>
    <user-info-endpoint>https://localhost:9443/oauth2/userinfo?schema=openid</user-info-endpoint>
    <logout-endpoint>https://localhost:9443/oidc/logout</logout-endpoint>
    <!--
        The Application Server trust-store configurations. This is used as a store for third-party
        SSL certificates for verification of credentials.
    -->
    <trust-store>
        <!--
            File path location of the Application Server trust-store. Environmental variable placeholders can
            be used within the file path provided.
         -->
        <location>${catalina.base}/conf/wso2/client-truststore.jks</location>
        <!-- The type of the trust-store. Types - JKS, PKCS11 and PKCS12 are recognized. -->
        <type>JKS</type>
        <!-- The alias of the private key. -->
        <key-alias>wso2carbon</key-alias>
        <!-- The password to unlock the trust-store file. -->
        <password>wso2carbon</password>
    </trust-store>

</oidc-config>

=== wso2-extensions/tomcat-extension-openidsso/samples/oidc-sample-apps/coffee-shop/src/main/webapp/META-INF/oidc-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.

 WSO2 Inc. licenses this file to you under the Apache License,
 Version 2.0 (the "License"); you may not use this file except
 in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<oidc-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://wso2.org/2016/oidc-config"
             xsi:schemaLocation="http://wso2.org/2016/oidc-config http://wso2.org/2016/oidc-config.xsd">

    <enable>true</enable>
    <client-id></client-id>
    <client-secret></client-secret>
    <redirect-uri>http://localhost:8080/coffee-shop/openid</redirect-uri>
    <scope>openid</scope>
    <claims></claims>
    <authentication-endpoint>https://localhost:9443/oauth2/authorize</authentication-endpoint>
    <token-endpoint>https://localhost:9443/oauth2/token</token-endpoint>
    <user-info-endpoint>https://localhost:9443/oauth2/userinfo</user-info-endpoint>
    <logout-endpoint>https://localhost:9443/oidc/logout</logout-endpoint>
    <trust-store>
        <location>${catalina.base}/webapps/coffee-shop/META-INF/client-truststore.jks</location>
        <type>JKS</type>
        <key-alias>wso2carbon</key-alias>
        <password>wso2carbon</password>
    </trust-store>

</oidc-config>

=== wso2-extensions/tomcat-extension-openidsso/modules/oidcsso/src/test/resources/testResources/oidcExtension/webapps/sample/META-INF/oidc-config.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.

 WSO2 Inc. licenses this file to you under the Apache License,
 Version 2.0 (the "License"); you may not use this file except
 in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing,
 software distributed under the License is distributed on an
 "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, either express or implied. See the License for the
 specific language governing permissions and limitations
 under the License.
-->
<oidc-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://wso2.org/2016/oidc-config"
             xsi:schemaLocation="http://wso2.org/2016/oidc-config http://wso2.org/2016/oidc-config.xsd">

    <enable>true</enable>
    <client-id>abdefghijklm_123415</client-id>
    <client-secret>6789nopqrstuvwxyz</client-secret>
    <redirect-uri>http://localhost:8080/foo-app/openid</redirect-uri>
    <scope>openid,profile</scope>
    <claims>address</claims>
    <authentication-endpoint>https://localhost:9443/oauth2/authorize</authentication-endpoint>
    <token-endpoint>https://localhost:9443/oauth2/token</token-endpoint>
    <user-info-endpoint>https://localhost:9443/oauth2/userinfo?schema=openid</user-info-endpoint>
    <logout-endpoint>https://localhost:9443/oidc/logout</logout-endpoint>
</oidc-config>
